### ISSUE TITLE
Add zwave2 to Weblate

### ISSUE THREAD

**Issue by AlCalzone** [ioBrokerTranslator/requests#1]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.zwave2
URL: https://github.com/AlCalzone/ioBroker.zwave2

**Remarks:**
I've added a webhook with the default settings, but it is not clear if those are correct.

**Comment by UncleSamSwiss** [comment]
Welcome to Weblate:
https://weblate.iobroker.net/projects/adapters/zwave2/
You can log in with your GitHub credentials.

**Comment by UncleSamSwiss** [comment]
Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

**Comment by AlCalzone** [comment]
done!
