### ISSUE TITLE
Add kecontact to Weblate

### ISSUE THREAD

**Issue by Sneak-L8** [ioBrokerTranslator/requests#101]
**Checklist:**

-   [X] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [X] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [ ] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate: kecontact
Name: ioBroker.kecontact
URL: https://github.com/iobroker-community-adapters/ioBroker.kecontact
License: Apache 2

**Remarks:**
No webhook option was available to set up these option. Perhaps a rights problem?

**Comment by mcm1957** [comment]
Please check and confirm that the last prerequisit ("Repository hook is confired") was done

**Comment by mcm1957** [comment]
webhook added

**Comment by mcm1957** [comment]
The adapter ioBroker.kecontact was added to Weblate:
https://weblate.iobroker.net/projects/adapters/kecontact/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
