### ISSUE TITLE
Add lightcontrol to Weblate

### ISSUE THREAD

**Issue by Schmakus** [ioBrokerTranslator/requests#106]
**Checklist:**

-   [X ] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [ X] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [ X] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.lightcontrol
URL: https://github.com/Schmakus/ioBroker.lightcontrol
License: MIT

**Remarks:**

**Comment by mcm1957** [comment]
The adapter ioBroker.lightcontrol was added to Weblate:
https://weblate.iobroker.net/projects/adapters/lightcontrol/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter

**Comment by mcm1957** [comment]
Please hek ENGLISH translations too. Some keys seem to have  o english text, i.e. "Add Light", "All", ...

![image](https://user-images.githubusercontent.com/28575778/210113445-739e9435-d14e-4fcf-b65b-ad3b51662444.png)
