### ISSUE TITLE
Add Roborock to Weblate

### ISSUE THREAD

**Issue by copystring** [ioBrokerTranslator/requests#107]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.roborock
URL: https://github.com/copystring/ioBroker.roborock
License: MIT

**Remarks:**
Translations are done in the robot files e.g.: https://github.com/copystring/ioBroker.roborock/blob/main/lib/roborock_vacuum_s4.js
I don't think this.states can be translated (yet?)

**Comment by mcm1957** [comment]
Translations MUST be done using gulp or adapter dev (npm run translate). All text to be translated MUST be located at i18n file (see first check). It seems that https://github.com/copystring/ioBroker.roborock/blob/main/admin/i18n/en/translations.json currently only contains the inital examples.

Translations in other files cannot be processed by weblate. Translations within other files are discoraged too. I do not think that Admin5 UI (json config) will respect roborock_vacuum.js for translation the gui labels.

Please see documentation: https://github.com/ioBrokerTranslator/doc#request-an-adapter-to-be-added-to-weblate

Please move all translations to the i18n files, commit those changes, perform first two checks again and assign issue to me afterwards.

**Comment by copystring** [comment]
OK. It seems I did not understood how this works. Translations are for the Admin5 UI only and not for the objects. That's OK.
I have corrected my files and pushed an Update to the repo. Let me know if this good now.

**Comment by copystring** [comment]
Unfortunately I don't have permission to assign the issue back to you.

**Comment by mcm1957** [comment]
OK, I'll look pover it this afternoon or tomorrow.

In general it should be possible to manage ANY text as accessing the text stored in the json files from code should be possible. Please ask at telegram how to perform this with minimum effort / best ompatibility.


https://t.me/+gsX-e8k4mLtmZjZk
https://t.me/ioBroker_development

**Comment by mcm1957** [comment]
The adapter ioBroker.roborock was added to Weblate:
https://weblate.iobroker.net/projects/adapters/roborock/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
