### ISSUE TITLE
Add ds18b20 to Weblate

### ISSUE THREAD

**Issue by crycode-de** [ioBrokerTranslator/requests#109]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.ds18b20
URL: https://github.com/crycode-de/ioBroker.ds18b20
License: MIT

**Remarks:**
Rewrite to v2.x
json files in `admin/i18n/*.json`

**Comment by mcm1957** [comment]
The adapter ioBroker.ds18b20 was added to Weblate:
https://weblate.iobroker.net/projects/adapters/fully-mqtt/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
