### ISSUE TITLE
Add ioBroker.plex to Weblate

### ISSUE THREAD

**Issue by ticaki** [ioBrokerTranslator/requests#110]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.plex
URL: https://github.com/iobroker-community-adapters/ioBroker.plex
License: MIT

**Remarks:**
Please add the webhook to the settings of ioBroker.plex. I dont have acress rights.

**Comment by UncleSamSwiss** [comment]
@mcm1957 can you please add this adapter? Thanks in advance

**Comment by mcm1957** [comment]
Yes ill do it latest next week due to holidays. Already communicated at telegram.

Its not really possible to do it on mobile and its not super prior.

Thanks for reminder.
