### ISSUE TITLE
Add klf200 to Weblate

### ISSUE THREAD

**Issue by MiSchroe** [ioBrokerTranslator/requests#114]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `npm run translate all` or `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.klf200
URL: https://github.com/MiSchroe/ioBroker.klf200
License: MIT

**Comment by mcm1957** [comment]
The adapter ioBroker.klf200  was added to Weblate:
https://weblate.iobroker.net/projects/adapters/klf200 /

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

Please check all translations of all languages known by you, correct translations and remove "needs translation" flag for those translations checked by you.

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
