### ISSUE TITLE
Add mydlink to Weblate

### ISSUE THREAD

**Issue by Garfonso** [ioBrokerTranslator/requests#2]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.mydlink
URL: https://github.com/iobroker-community-adapters/ioBroker.mydlink

**Remarks:**
First adapter for testing weblate. 😄

**Comment by UncleSamSwiss** [comment]
Welcome to Weblate:
https://weblate.iobroker.net/projects/adapters/mydlink/
You can log in with your GitHub credentials.

**Comment by UncleSamSwiss** [comment]
Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd
