### ISSUE TITLE
Add admin to Weblate

### ISSUE THREAD

**Issue by Apollon77** [ioBrokerTranslator/requests#34]
**Checklist:**

-   [X] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [X] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [X] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)
-  [x] done

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.admin
URL: https://github.com/ioBroker/ioBroker.admin

**Remarks:**
Location i18n files for react UI: https://github.com/ioBroker/ioBroker.admin/tree/master/src-rx/src/i18n

**Comment by UncleSamSwiss** [comment]
Currently there are four different translations in the repo:
- admin/i18n/*/translations.json
- src-admin/src/i18n/*.json
- src-rx/src/i18n/*.json
- src/i18n/*/translations.json

Should we really create 4 translation components or wouldn't it be good to have everything in one place?

**Comment by Apollon77** [comment]
For Admin5 we only need:
* admin/i18n/*/translations.json
* src-rx/src/i18n/*.json
The other two are "old Admin4" and irrelevant for the future

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.admin was added to Weblate:
https://weblate.iobroker.net/projects/adapters/admin/
https://weblate.iobroker.net/projects/adapters/admin-web/ (linked to the above)

Please add **both** badges for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
