### ISSUE TITLE
Add devices to Weblate

### ISSUE THREAD

**Issue by Apollon77** [ioBrokerTranslator/requests#37]
**Checklist:**

-   [X] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [X] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)
-  [x] done
**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.devices
URL: https://github.com/ioBroker/ioBroker.devices

**Remarks:**
i18n file location react: https://github.com/ioBroker/ioBroker.devices/tree/master/src/src/i18n

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.devices was added to Weblate:
https://weblate.iobroker.net/projects/adapters/devices/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
