### ISSUE TITLE
Add adapter-react to Weblate

### ISSUE THREAD

**Issue by Apollon77** [ioBrokerTranslator/requests#38]
**Checklist:**

-   [X] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [X] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: adapter-react
URL: https://github.com/ioBroker/adapter-react
License: MIT

**Remarks:**
i18n files in https://github.com/ioBroker/adapter-react/tree/master/src/i18n

**Comment by UncleSamSwiss** [comment]
The adapter adapter-react was added to Weblate:
https://weblate.iobroker.net/projects/tools/adapter-react/

Please add the badge for Weblate translations to your repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
