### ISSUE TITLE
Add ESPHome to Weblate

### ISSUE THREAD

**Issue by DutchmanNL** [ioBrokerTranslator/requests#4]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.esphome
URL: https://github.com/DrozmotiX/ioBroker.esphome

**Remarks:**
Thank you :)

PS: Webhook not directly added but on organization root :)

**Comment by UncleSamSwiss** [comment]
Added the adapter to Weblate, but please make sure you add all strings: https://github.com/DrozmotiX/ioBroker.esphome/issues/41
