### ISSUE TITLE
Add ioBroker.epson_ecotank_et_2750 to Weblate

### ISSUE THREAD

**Issue by o0shojo0o** [ioBrokerTranslator/requests#41]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.epson_ecotank_et_2750
URL: https://github.com/o0shojo0o/ioBroker.epson_ecotank_et_2750
License: MIT

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.epson_ecotank_et_2750 was added to Weblate:
https://weblate.iobroker.net/projects/adapters/epson_ecotank_et_2750/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
