### ISSUE TITLE
Add deconz to Weblate

### ISSUE THREAD

**Issue by Jey-Cee** [ioBrokerTranslator/requests#43]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.deconz
URL: https://github.com/iobroker-community-adapters/ioBroker.deconz
License: MIT

**Remarks:**
None

**Comment by UncleSamSwiss** [comment]
Your `master` branch is missing the `i18n` files as requested in the issue template:
The adapter contains the i18n files in a separate folder with the default naming scheme
Please run `gulp adminWords2languages` and commit those files

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.deconz was added to Weblate:
https://weblate.iobroker.net/projects/adapters/deconz/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
