### ISSUE TITLE
Add Meteoalarm to Weblate

### ISSUE THREAD

**Issue by jack-blackson** [ioBrokerTranslator/requests#45]
**Checklist:**

-   [ ] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [ ] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [ ] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.meteoalarm
URL: https://github.com/jack-blackson/ioBroker.meteoalarm
License: MIT

**Remarks:**

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.meteoalarm was added to Weblate:
https://weblate.iobroker.net/projects/adapters/meteoalarm/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
