### ISSUE TITLE
Add Countdown to Weblate

### ISSUE THREAD

**Issue by jack-blackson** [ioBrokerTranslator/requests#46]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.countdown
URL: https://github.com/jack-blackson/ioBroker.countdown
License: MIT

**Remarks:**

**Comment by UncleSamSwiss** [comment]
Please complete the checklist.
You are missing the i18n folder.

**Comment by jack-blackson** [comment]
This should be fixed now - sorry.

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.countdown was added to Weblate:
https://weblate.iobroker.net/projects/adapters/countdown/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
