### ISSUE TITLE
Add dwd to Weblate

### ISSUE THREAD

**Issue by Apollon77** [ioBrokerTranslator/requests#53]
**Checklist:**

-   [X] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [X] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [X] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.dwd
URL: https://github.com/ioBroker/ioBroker.dwd
License: MIT

**Remarks:**

**Comment by UncleSamSwiss** [comment]
Sorry, your file is corrupt:
> Could not parse 1 matched file. admin/i18n/de/translations.json: JSONDecodeError("Expecting ',' delimiter: line 6 column 3 (char 181)")

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.dwd was added to Weblate:
https://weblate.iobroker.net/projects/adapters/dwd/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
