### ISSUE TITLE
Add fahrplan and slideshow to Weblate

### ISSUE THREAD

**Issue by gaudes** [ioBrokerTranslator/requests#6]
**Checklist:**

-   [X] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [X] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [X] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapters to Weblate:
Name: ioBroker.fahrplan
URL: https://github.com/gaudes/ioBroker.fahrplan

Name: ioBroker.slideshow
URL: https://github.com/gaudes/ioBroker.slideshow

Thanks and regards,

Ralf

**Comment by UncleSamSwiss** [comment]
Adapter ioBroker fahrplan was added to Weblate:
https://weblate.iobroker.net/projects/adapters/fahrplan/

**Comment by UncleSamSwiss** [comment]
Adapter ioBroker.slideshow was added to Weblate:
https://weblate.iobroker.net/projects/adapters/slideshow/

Have fun translating :)
