### ISSUE TITLE
Add tahoma & schwoerer-ventcube to Weblate

### ISSUE THREAD

**Issue by Excodibur** [ioBrokerTranslator/requests#69]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:

Name: ioBroker.tahoma
URL: https://github.com/Excodibur/ioBroker.tahoma
License: MIT

Name: ioBroker.schwoerer-ventcube
URL: https://github.com/Excodibur/ioBroker.schwoerer-ventcube
License: MIT

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.tahoma was added to Weblate:
https://weblate.iobroker.net/projects/adapters/tahoma/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.schwoerer-ventcube was added to Weblate:
https://weblate.iobroker.net/projects/adapters/schwoerer-ventcube/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter

**Comment by Excodibur** [comment]
Thanks! :-)
