### ISSUE TITLE
Add iobroker.iqontrol to Weblate

### ISSUE THREAD

**Issue by sbormann** [ioBrokerTranslator/requests#70]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.iqontrol
URL: https://github.com/sbormann/ioBroker.iqontrol
License: MIT

**Remarks:**

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.iqontrol was added to Weblate:
https://weblate.iobroker.net/projects/adapters/iqontrol/
https://weblate.iobroker.net/projects/adapters/iqontrol-web/

**IMPORANT:** you are the only adapter in Weblate that is using Web without React (for now), so the script in Weblate will unfortunately not automatically move the translations from www/i18n into www/words.js. You have two options:
- do it manually after each PR you get from Weblate (call `gulp wwwLanguages2words` in the root of your project)
- change your gulpfile to call wwwLanguages2words when adminLanguages2words is called

Sorry for the inconvenience!

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
