### ISSUE TITLE
Add odl to Weblate

### ISSUE THREAD

**Issue by crycode-de** [ioBrokerTranslator/requests#83]
**Checklist:**

-   [x] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [x] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.odl
URL: https://github.com/crycode-de/ioBroker.odl
License: MIT

**Remarks:**

* New React-UI
* i18n files in [admin/src/i18n](https://github.com/crycode-de/ioBroker.odl/tree/master/admin/src/i18n)
* Uses latest `@iobroker/adapter-dev`

**Comment by mcm1957** [comment]
The adapter ioBroker.odl was added to Weblate:
https://weblate.iobroker.net/projects/adapters/odl/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
