### ISSUE TITLE
Add snmp to Weblate

### ISSUE THREAD

**Issue by Apollon77** [ioBrokerTranslator/requests#84]
**Checklist:**

-   [X] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [X] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [X] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.snmp
URL: https://github.com/iobroker-community-adapters/ioBroker.snmp
License: MIT

**Remarks:**

**Comment by mcm1957** [comment]
duplicated by #104
