### ISSUE TITLE
Add discovery to Weblate

### ISSUE THREAD

**Issue by Apollon77** [ioBrokerTranslator/requests#9]
**Checklist:**

-   [X] The adapter contains the i18n files in a separate folder with the default naming scheme
-   [X] All translation JSON files are up-to-date (call `gulp translateAndUpdateWordsJS` and commit and push those changes to master/main)
-   [x] Repository hook is configured on GitHub (set the Payload URL to `https://weblate.iobroker.net/hooks/github/`)
-   [x] translate done

**Request:**

Please add the following adapter to Weblate:
Name: ioBroker.discovery
URL: https://github.com/ioBroker/ioBroker.discovery

**Remarks:**

**Comment by UncleSamSwiss** [comment]
The adapter ioBroker.discovery was added to Weblate:
https://weblate.iobroker.net/projects/adapters/discovery/

Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

From now on, please follow these guidelines:
https://github.com/ioBrokerTranslator/doc#maintenance-of-your-adapter
